In [1]:
# import numpy
# create array x

In [32]:
import numpy as np


x= np.array ([6, 12, 14, 16, 18, 33, 49, 62, 77])


In [12]:
print x

[ 6 12 14 16 18 33 49 62 77]


In [2]:
# print the shape of x

In [13]:
print x.shape

(9,)


In [3]:
# create a two dimensional array

In [33]:
x2d = np.array ([[6, 12, 14, 16, 18, 33, 49, 62, 77],[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [4]:
# print shape of 2d array

In [24]:
print x2d

[[ 6 12 14 16 18 33 49 62 77]
 [ 1  2  3  4  5  6  7  8  9]]


In [5]:
# reshape the array to 2 x 6

In [25]:
print x2d.shape

(2, 9)


In [36]:
print x2d.reshape (x(2,6))

TypeError: 'numpy.ndarray' object is not callable

In [35]:
x2d = np.reshape(x2d(2,6)) 

print x2d

TypeError: 'numpy.ndarray' object is not callable

In [6]:
# reshape the array to 1 x 12

In [7]:
# transpose the array

In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6